Update for multi-system PGXL configuration
Data collection still needs to be updated.

diff --git a/scripts/dbt3-sysstats b/scripts/dbt3-sysstats
--- a/scripts/dbt3-sysstats
+++ b/scripts/dbt3-sysstats
@@ -7,6 +7,28 @@
 #               2002-2014 Mark Wong
 #               2014      2ndQuadrant, Ltd.
 
+start_remote_pidstat()
+{
+	HOST=$1
+
+	PIDSTATFILE="$OUTPUT_DIR/$HOST/pidstat.txt"
+	ssh $HOST << __EOF__
+mkdir -p $SARDIR
+$CMD $SAMPLE_LENGTH > $PIDSTATFILE
+__EOF__
+}
+
+start_remote_sar()
+{
+	HOST=$1
+
+	SARDIR="$OUTPUT_DIR/$HOST"
+	ssh $HOST << __EOF__
+mkdir -p $SARDIR
+$SAR -o $SARDIR/sar_raw.out $SAMPLE_LENGTH > $SARDIR/sar.txt
+__EOF__
+}
+
 if [ $# -lt 1 ]; then
     echo "usage: $0 --outdir <output_dir> -sample <sample_length>"
     echo "	<output_dir> will be created if it doesn't exist"
@@ -96,8 +118,35 @@ mkdir -p $OUTPUT_DIR
 echo "starting system statistics data collection"
 
 # collect all sar data in binary form
-${SAR} -o ${OUTPUT_DIR}/sar_raw.out ${SAMPLE_LENGTH} > ${OUTPUT_DIR}/sar.txt &
-echo "$!" > ${OUTPUT_DIR}/sar.pid
+SARDIR="$OUTPUT_DIR/$GTMHOST"
+mkdir -p $SARDIR
+$SAR -o $SARDIR/sar_raw.out $SAMPLE_LENGTH > $SARDIR/sar.txt &
+SARPIDS="$!"
 
-${PIDSTAT} -h -l -d -r -s -u -w ${SAMPLE_LENGTH} > ${OUTPUT_DIR}/pidstat.txt &
+for HOSTNAME in $HOSTNAMES; do
+	start_remote_sar $HOSTNAME &
+	SARPIDS="$SARPIDS $!"
+done
+
+echo $SARPIDS > $OUTPUT_DIR/sar.pid
+
+PIDSTATFILE="$OUTPUT_DIR/$GTMHOST/pidstat.txt"
+CMD="$PIDSTAT -h -l -d -r -s -u -w"
+$CMD 1 1 > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+	CMD="$PIDSTAT -h -l -d -r -u -w"
+	$CMD 1 1 > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "WARNING: Cannot determine propper pidstat flags"
+		CMD="true"
+	fi
+fi
+
+$CMD $SAMPLE_LENGTH > $PIDSTATFILE &
+PIDSTATPIDS="$!"
+for HOSTNAME in $HOSTNAMES; do
+	start_remote_pidstat $HOSTNAME &
+	PIDSTATPIDS="$PIDSTATPIDS $!"
+done
+
 echo "$!" > ${OUTPUT_DIR}/pidstat.pid
